### PR TITLE
Modified abs reference of pycryptodomex==3.11.0 to nearest compatible.

### PR DESCRIPTION
**Pull request by loucksg**
aiming to fix compatibility problem with the python crypto library install within the docker container.

### CODE REVIEW

**Comment by kilador** [comment]
I tried your solution: changing "==" by "~=" but still get the same error. Any other idea?

**Comment by loucksg** [comment]
Hi Kilador,Ok apparently the packages are no more and HA does not allow us to build. There are a couple streams of work on it, there is a sungather discord chat we’re working over there I’ll update this ticket with the results as well.GuyGuy's mobileOn 16 Jan 2024, at 12:03 pm, kilador ***@***.***> wrote:﻿
I tried your solution: changing "==" by "~=" but still get the same error. Any other idea?

**Review by DanelRod — APPROVED** [review]

**Comment by oleg-d** [comment]
Can this be merged and new release made with this fix? There's quite a few people waiting to try this integration out as the GoSungrow one has been broken.

**Comment by roabyd** [comment]
@oleg-d unfortunately this PR would not fix this issue (I cloned the repo and tried updating it myself). It looks like there is a bigger issue here as per @loucksg's comment. Here's hoping a fix can be found soon

**Comment by roabyd** [comment]
image

**Pull request closed without merging**
